2019-04-04 18:42:07,999 ERROR    django.request Internal Server Error: /sso/metadata/saml/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/lib/python2.7/site-packages/awx/wsgi.py", line 71, in _legacy_get_response
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/lib/python2.7/site-packages/awx/sso/views.py", line 64, in get
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 27, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry
